/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fr.ufrsciencestech.panier.view;

import fr.ufrsciencestech.panier.controler.Controleur;
import fr.ufrsciencestech.panier.controler.ControleurFruit;
import fr.ufrsciencestech.panier.model.FruitSimple;
import fr.ufrsciencestech.panier.model.Panier;
import fr.ufrsciencestech.panier.model.OrigineProduit;
import fr.ufrsciencestech.panier.model.SaladeFruits;
import fr.ufrsciencestech.panier.model.TypeFruitSimple;
import fr.ufrsciencestech.panier.model.TypeProduit;
import java.util.Observable;

import javax.swing.*;

/**
 *
 * @author pt454976
 */
public class VueAjoutSaladesFruit extends javax.swing.JFrame implements VueG{
    private Panier mPanier;
    private VuePanier mVP;
    private Controleur mControleur;

    /**
     * Creates new form VueAjoutFruit
     */
    public VueAjoutSaladesFruit(Panier panier, VuePanier vuePanier, Controleur controleur) {
        initComponents();
        this.mPanier = panier;
        this.mVP = vuePanier;
        this.mControleur = controleur;
                
        initDatas();
    }
    
    void initDatas(){
        DefaultComboBoxModel<OrigineProduit> modelOrigineSalade = new DefaultComboBoxModel<>(OrigineProduit.values());
        this.jComboBoxOrigineSalade.setModel((ComboBoxModel) modelOrigineSalade);
    }
    
    boolean jTextFieldPrixValide(){
        try{
            String text = this.jTextFieldPrixSalade.getText();
            double prix = Double.parseDouble(text);
            return true;
        }catch(Exception e){
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTypeOrigineFruitSimple = new javax.swing.JPanel();
        labelPrixSalade = new javax.swing.JLabel();
        jTextFieldPrixSalade = new javax.swing.JTextField();
        labelOrigineSalade = new javax.swing.JLabel();
        jComboBoxOrigineSalade = new javax.swing.JComboBox<>();
        panelPrixQteFruitSimple = new javax.swing.JPanel();
        panelBoutonsValiderAnnuler = new javax.swing.JPanel();
        jButtonValiderFruitSimple = new javax.swing.JButton();
        jButtonAnnulerFruitSimple = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelPrixSalade.setText("Prix salade : ");
        panelTypeOrigineFruitSimple.add(labelPrixSalade);

        jTextFieldPrixSalade.setPreferredSize(new java.awt.Dimension(100, 30));
        panelTypeOrigineFruitSimple.add(jTextFieldPrixSalade);

        labelOrigineSalade.setText("Origine salade : ");
        panelTypeOrigineFruitSimple.add(labelOrigineSalade);

        panelTypeOrigineFruitSimple.add(jComboBoxOrigineSalade);

        getContentPane().add(panelTypeOrigineFruitSimple, java.awt.BorderLayout.NORTH);
        getContentPane().add(panelPrixQteFruitSimple, java.awt.BorderLayout.CENTER);

        jButtonValiderFruitSimple.setText("Valider");
        jButtonValiderFruitSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderFruitSimpleActionPerformed(evt);
            }
        });
        panelBoutonsValiderAnnuler.add(jButtonValiderFruitSimple);

        jButtonAnnulerFruitSimple.setText("Annuler");
        jButtonAnnulerFruitSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerFruitSimpleActionPerformed(evt);
            }
        });
        panelBoutonsValiderAnnuler.add(jButtonAnnulerFruitSimple);

        getContentPane().add(panelBoutonsValiderAnnuler, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderFruitSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderFruitSimpleActionPerformed
        // TODO add your handling code here:
        if(this.jTextFieldPrixValide()){
            try{
                
                double prixJus = Double.parseDouble(this.jTextFieldPrixSalade.getText());
                OrigineProduit origineJus = (OrigineProduit) this.jComboBoxOrigineSalade.getSelectedItem();
                SaladeFruits salade = new SaladeFruits(prixJus,origineJus);
                
                ControleurFruit cf = (ControleurFruit)this.mVP.getControleur();
                try{
                    cf.ajoutProduit(salade);
                }catch (Exception e){
                    System.err.println(e);
                }
                
            }catch(Exception e){
                System.err.println(e);
            }
            this.dispose();
            this.pack();
        }else{
            System.err.println("Vous devez renseigner le prix du fruit correctement !\nOu alors le fruit est boycotté !");
        }
    }//GEN-LAST:event_jButtonValiderFruitSimpleActionPerformed

    private void jButtonAnnulerFruitSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerFruitSimpleActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.pack();
    }//GEN-LAST:event_jButtonAnnulerFruitSimpleActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnulerFruitSimple;
    private javax.swing.JButton jButtonValiderFruitSimple;
    private javax.swing.JComboBox<String> jComboBoxOrigineSalade;
    private javax.swing.JTextField jTextFieldPrixSalade;
    private javax.swing.JLabel labelOrigineSalade;
    private javax.swing.JLabel labelPrixSalade;
    private javax.swing.JPanel panelBoutonsValiderAnnuler;
    private javax.swing.JPanel panelPrixQteFruitSimple;
    private javax.swing.JPanel panelTypeOrigineFruitSimple;
    // End of variables declaration//GEN-END:variables

    public Panier getPanier(){
        return this.mPanier;
    }
    
    public VuePanier getVuePanier(){
        return this.mVP;
    }
    
    public void setPanier(Panier panier){
        this.mPanier = panier;
    }
    
    public void setVuePanier(VuePanier vuePanier){
        this.mVP = vuePanier;
    }
    
    public Controleur getControleur(){
        return this.mControleur;
    }
    
    @Override
    public void addControleur(Controleur c){
        this.mControleur=c;
    }
    
    @Override
    public void update(Observable m, Object o){
        this.mPanier= (Panier)o;
        this.mVP.remplirListe();
    }
}
