/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fr.ufrsciencestech.panier.view;

import fr.ufrsciencestech.panier.model.Panier;
import fr.ufrsciencestech.panier.model.OrigineProduit;
import fr.ufrsciencestech.panier.model.TypeProduit;

import javax.swing.*;

/**
 *
 * @author Utilisateur
 */
public class VueAjoutFruit extends javax.swing.JFrame {
    
    Panier mPanier;

    /**
     * Creates new form VueAjoutFruit
     */
    public VueAjoutFruit() {
        initComponents();
        
        this.mPanier = new Panier(10);
        
        initDatas();
    }
    
    void initDatas(){
        DefaultComboBoxModel<OrigineProduit> modelOrigine = new DefaultComboBoxModel<>(OrigineProduit.values());
        this.jComboBoxOrigineFruitSimple.setModel((ComboBoxModel) modelOrigine);
        
        DefaultComboBoxModel<TypeProduit> modelType = new DefaultComboBoxModel<>(TypeProduit.values());
        this.jComboBoxTypeFruitSimple.setModel((ComboBoxModel) modelType);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTypeOrigineFruitSimple = new javax.swing.JPanel();
        labelTypeFruitSimple = new javax.swing.JLabel();
        jComboBoxTypeFruitSimple = new javax.swing.JComboBox<>();
        labelOrigineFruitSimple = new javax.swing.JLabel();
        jComboBoxOrigineFruitSimple = new javax.swing.JComboBox<>();
        panelPrixQteFruitSimple = new javax.swing.JPanel();
        labelPrixFruitSimple = new javax.swing.JLabel();
        jTextFieldPrixFruitSimple = new javax.swing.JTextField();
        labelQteFruitSimple = new javax.swing.JLabel();
        jSpinnerQteFruitSimple = new javax.swing.JSpinner();
        panelBoutonsValiderAnnuler = new javax.swing.JPanel();
        jButtonValiderFruitSimple = new javax.swing.JButton();
        jButtonAnnulerFruitSimple = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(3, 1));

        labelTypeFruitSimple.setText("Type du fruit : ");
        panelTypeOrigineFruitSimple.add(labelTypeFruitSimple);

        panelTypeOrigineFruitSimple.add(jComboBoxTypeFruitSimple);

        labelOrigineFruitSimple.setText("Origine du fruit : ");
        panelTypeOrigineFruitSimple.add(labelOrigineFruitSimple);

        panelTypeOrigineFruitSimple.add(jComboBoxOrigineFruitSimple);

        getContentPane().add(panelTypeOrigineFruitSimple);

        labelPrixFruitSimple.setText("Prix du fruit : ");
        panelPrixQteFruitSimple.add(labelPrixFruitSimple);

        jTextFieldPrixFruitSimple.setPreferredSize(new java.awt.Dimension(100, 30));
        panelPrixQteFruitSimple.add(jTextFieldPrixFruitSimple);

        labelQteFruitSimple.setText("Quantité : ");
        panelPrixQteFruitSimple.add(labelQteFruitSimple);

        jSpinnerQteFruitSimple.setPreferredSize(new java.awt.Dimension(40, 30));
        panelPrixQteFruitSimple.add(jSpinnerQteFruitSimple);

        getContentPane().add(panelPrixQteFruitSimple);

        jButtonValiderFruitSimple.setText("Valider");
        panelBoutonsValiderAnnuler.add(jButtonValiderFruitSimple);

        jButtonAnnulerFruitSimple.setText("Annuler");
        panelBoutonsValiderAnnuler.add(jButtonAnnulerFruitSimple);

        getContentPane().add(panelBoutonsValiderAnnuler);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueAjoutFruit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueAjoutFruit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueAjoutFruit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueAjoutFruit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VueAjoutFruit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnulerFruitSimple;
    private javax.swing.JButton jButtonValiderFruitSimple;
    private javax.swing.JComboBox<String> jComboBoxOrigineFruitSimple;
    private javax.swing.JComboBox<String> jComboBoxTypeFruitSimple;
    private javax.swing.JSpinner jSpinnerQteFruitSimple;
    private javax.swing.JTextField jTextFieldPrixFruitSimple;
    private javax.swing.JLabel labelOrigineFruitSimple;
    private javax.swing.JLabel labelPrixFruitSimple;
    private javax.swing.JLabel labelQteFruitSimple;
    private javax.swing.JLabel labelTypeFruitSimple;
    private javax.swing.JPanel panelBoutonsValiderAnnuler;
    private javax.swing.JPanel panelPrixQteFruitSimple;
    private javax.swing.JPanel panelTypeOrigineFruitSimple;
    // End of variables declaration//GEN-END:variables
}
