/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fr.ufrsciencestech.panier.view;

import fr.ufrsciencestech.panier.controler.Controleur;
import fr.ufrsciencestech.panier.model.FruitFactory;
import fr.ufrsciencestech.panier.model.OrigineProduit;
import fr.ufrsciencestech.panier.model.TypeFruitSimple;

import javax.swing.*;

/**
 * Vue pour ajouter un fruit dans le panier
 * @author pt454976
 */
public class VueAjoutFruit extends javax.swing.JFrame{
    /**
     * Vue parente
     */
    private VuePanier mVP;
    /**
     * Controleur de la vue
     */
    private Controleur mControleur;
    
    /**
    * Quantite de fruit a rajouter
    */
    private int mQuantite;

    /**
     * Construteur de la vue
     * @param vuePanier le parent
     * @param controleur le controleur
     */
    public VueAjoutFruit(VuePanier vuePanier, Controleur controleur) {
        initComponents();
        this.mVP = vuePanier;
        this.mControleur = controleur;
        this.jSpinnerQteFruitSimple.setModel(new SpinnerNumberModel(0, 0, this.mVP.getQuantiteRestante(), 1));
        this.mQuantite = 0;
                
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        initDatas();
    }
    
    /**
     * Initialise les models des combos box a partir des enumerations
     */
    void initDatas(){
        DefaultComboBoxModel<OrigineProduit> modelOrigine = new DefaultComboBoxModel<>(OrigineProduit.values());
        this.jComboBoxOrigineFruitSimple.setModel((ComboBoxModel) modelOrigine);
        
        DefaultComboBoxModel<TypeFruitSimple> modelType = new DefaultComboBoxModel<>(TypeFruitSimple.values());
        this.jComboBoxTypeFruitSimple.setModel((ComboBoxModel) modelType);
    }
    
    /**
     * Verifie que le prix est valide
     * @return 
     */
    boolean jTextFieldPrixValide(){
        try{
            String text = this.jTextFieldPrixFruitSimple.getText();
            double prix = Double.parseDouble(text);
            return true;
        }catch(Exception e){
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTypeOrigineFruitSimple = new javax.swing.JPanel();
        labelTypeFruitSimple = new javax.swing.JLabel();
        jComboBoxTypeFruitSimple = new javax.swing.JComboBox<>();
        labelOrigineFruitSimple = new javax.swing.JLabel();
        jComboBoxOrigineFruitSimple = new javax.swing.JComboBox<>();
        panelPrixQteFruitSimple = new javax.swing.JPanel();
        labelPrixFruitSimple = new javax.swing.JLabel();
        jTextFieldPrixFruitSimple = new javax.swing.JTextField();
        labelQteFruitSimple = new javax.swing.JLabel();
        jSpinnerQteFruitSimple = new javax.swing.JSpinner();
        panelBoutonsValiderAnnuler = new javax.swing.JPanel();
        jButtonValiderFruitSimple = new javax.swing.JButton();
        jButtonAnnulerFruitSimple = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ajout fruit");
        setPreferredSize(new java.awt.Dimension(500, 120));
        setSize(new java.awt.Dimension(500, 120));

        labelTypeFruitSimple.setText("Type du fruit : ");
        panelTypeOrigineFruitSimple.add(labelTypeFruitSimple);

        panelTypeOrigineFruitSimple.add(jComboBoxTypeFruitSimple);

        labelOrigineFruitSimple.setText("Origine du fruit : ");
        panelTypeOrigineFruitSimple.add(labelOrigineFruitSimple);

        panelTypeOrigineFruitSimple.add(jComboBoxOrigineFruitSimple);

        getContentPane().add(panelTypeOrigineFruitSimple, java.awt.BorderLayout.NORTH);

        labelPrixFruitSimple.setText("Prix du fruit : ");
        panelPrixQteFruitSimple.add(labelPrixFruitSimple);

        jTextFieldPrixFruitSimple.setPreferredSize(new java.awt.Dimension(100, 30));
        panelPrixQteFruitSimple.add(jTextFieldPrixFruitSimple);

        labelQteFruitSimple.setText("Quantité : ");
        panelPrixQteFruitSimple.add(labelQteFruitSimple);

        jSpinnerQteFruitSimple.setPreferredSize(new java.awt.Dimension(40, 30));
        jSpinnerQteFruitSimple.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerQteFruitSimpleStateChanged(evt);
            }
        });
        panelPrixQteFruitSimple.add(jSpinnerQteFruitSimple);

        getContentPane().add(panelPrixQteFruitSimple, java.awt.BorderLayout.CENTER);

        jButtonValiderFruitSimple.setText("Valider");
        jButtonValiderFruitSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderFruitSimpleActionPerformed(evt);
            }
        });
        panelBoutonsValiderAnnuler.add(jButtonValiderFruitSimple);

        jButtonAnnulerFruitSimple.setText("Annuler");
        jButtonAnnulerFruitSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerFruitSimpleActionPerformed(evt);
            }
        });
        panelBoutonsValiderAnnuler.add(jButtonAnnulerFruitSimple);

        getContentPane().add(panelBoutonsValiderAnnuler, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evenement sur le spinner pour modifer la quantite
     * @param evt 
     */
    private void jSpinnerQteFruitSimpleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerQteFruitSimpleStateChanged
        // TODO add your handling code here:
        this.mQuantite = (Integer)this.jSpinnerQteFruitSimple.getModel().getValue();
    }//GEN-LAST:event_jSpinnerQteFruitSimpleStateChanged

    /**
     * Appuie sur le bouton de validation, recupere les donnees pour creer le fruit et l'ajouter au panier
     * @param evt 
     */
    private void jButtonValiderFruitSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderFruitSimpleActionPerformed
        double prix = Double.parseDouble(this.jTextFieldPrixFruitSimple.getText());
        TypeFruitSimple tfs = (TypeFruitSimple) this.jComboBoxTypeFruitSimple.getSelectedItem();
        OrigineProduit op = (OrigineProduit) this.jComboBoxOrigineFruitSimple.getSelectedItem();
                
        if(this.jTextFieldPrixValide() && this.mVP.getBoycotte() != op){
            try{
                for(int i = 0; i < this.mQuantite; i++){
                    try{
                        this.mVP.getControleur().ajoutProduit(FruitFactory.creerFruitSimple(prix, op, tfs));
                    }catch (Exception e){
                        System.err.println(e);
                    }
                }
            }catch(Exception e){
                System.err.println(e);
            }
            this.dispose();
            this.pack();
        }else{
            System.err.println("Vous devez renseigner le prix du fruit correctement !\nOu alors le fruit est boycotté !");
        }
    }//GEN-LAST:event_jButtonValiderFruitSimpleActionPerformed

    /**
     * Bouton d'annulation, ferme la vue
     * @param evt 
     */
    private void jButtonAnnulerFruitSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerFruitSimpleActionPerformed
        this.dispose();
        this.pack();
    }//GEN-LAST:event_jButtonAnnulerFruitSimpleActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnulerFruitSimple;
    private javax.swing.JButton jButtonValiderFruitSimple;
    private javax.swing.JComboBox<String> jComboBoxOrigineFruitSimple;
    private javax.swing.JComboBox<String> jComboBoxTypeFruitSimple;
    private javax.swing.JSpinner jSpinnerQteFruitSimple;
    private javax.swing.JTextField jTextFieldPrixFruitSimple;
    private javax.swing.JLabel labelOrigineFruitSimple;
    private javax.swing.JLabel labelPrixFruitSimple;
    private javax.swing.JLabel labelQteFruitSimple;
    private javax.swing.JLabel labelTypeFruitSimple;
    private javax.swing.JPanel panelBoutonsValiderAnnuler;
    private javax.swing.JPanel panelPrixQteFruitSimple;
    private javax.swing.JPanel panelTypeOrigineFruitSimple;
    // End of variables declaration//GEN-END:variables

   
}
