/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fr.ufrsciencestech.panier.view;

import fr.ufrsciencestech.panier.controler.Controleur;
import fr.ufrsciencestech.panier.controler.ControleurFruit;
import fr.ufrsciencestech.panier.model.FruitFactory;
import fr.ufrsciencestech.panier.model.FruitSimple;
import fr.ufrsciencestech.panier.model.Panier;
import fr.ufrsciencestech.panier.model.OrigineProduit;
import fr.ufrsciencestech.panier.model.SaladeFruits;
import fr.ufrsciencestech.panier.model.TypeFruitSimple;
import fr.ufrsciencestech.panier.model.TypeProduit;
import java.util.ArrayList;
import java.util.Observable;

import javax.swing.*;

/**
 *
 * @author pt454976
 */
public class VueAjoutSaladesFruit extends javax.swing.JFrame implements VueG{
    private VuePanier mVP;
    private Controleur mControleur;
    private ArrayList<FruitSimple> fruits = new ArrayList<FruitSimple>();

    /**
     * Creates new form VueAjoutFruit
     */
    public VueAjoutSaladesFruit(VuePanier vuePanier, Controleur controleur) {
        initComponents();
        this.mVP = vuePanier;
        this.mControleur = controleur;
                
        initDatas();
    }
    
    void initDatas(){
        DefaultComboBoxModel<OrigineProduit> modelOrigineSalade = new DefaultComboBoxModel<>(OrigineProduit.values());
        this.jComboBoxOrigineSalade.setModel((ComboBoxModel) modelOrigineSalade);
    }
    
    boolean jTextFieldPrixValide(){
        try{
            String text = this.jTextFieldPrixSalade.getText();
            double prix = Double.parseDouble(text);
            return true;
        }catch(Exception e){
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTypeOrigineFruitSimple = new javax.swing.JPanel();
        labelPrixSalade = new javax.swing.JLabel();
        jTextFieldPrixSalade = new javax.swing.JTextField();
        labelOrigineSalade = new javax.swing.JLabel();
        jComboBoxOrigineSalade = new javax.swing.JComboBox<>();
        panelPrixQteFruitSimple = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonAjoutFruit = new javax.swing.JButton();
        panelBoutonsValiderAnnuler = new javax.swing.JPanel();
        jButtonValiderFruitSimple = new javax.swing.JButton();
        jButtonAnnulerFruitSimple = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelPrixSalade.setText("Prix salade : ");
        panelTypeOrigineFruitSimple.add(labelPrixSalade);

        jTextFieldPrixSalade.setPreferredSize(new java.awt.Dimension(100, 30));
        panelTypeOrigineFruitSimple.add(jTextFieldPrixSalade);

        labelOrigineSalade.setText("Origine salade : ");
        panelTypeOrigineFruitSimple.add(labelOrigineSalade);

        panelTypeOrigineFruitSimple.add(jComboBoxOrigineSalade);

        getContentPane().add(panelTypeOrigineFruitSimple, java.awt.BorderLayout.NORTH);

        jLabel1.setText("Fruits dans la salade :");
        panelPrixQteFruitSimple.add(jLabel1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        panelPrixQteFruitSimple.add(jScrollPane1);

        jButtonAjoutFruit.setText("Ajouter un fruit");
        jButtonAjoutFruit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjoutFruitActionPerformed(evt);
            }
        });
        panelPrixQteFruitSimple.add(jButtonAjoutFruit);

        getContentPane().add(panelPrixQteFruitSimple, java.awt.BorderLayout.CENTER);

        jButtonValiderFruitSimple.setText("Valider");
        jButtonValiderFruitSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderFruitSimpleActionPerformed(evt);
            }
        });
        panelBoutonsValiderAnnuler.add(jButtonValiderFruitSimple);

        jButtonAnnulerFruitSimple.setText("Annuler");
        jButtonAnnulerFruitSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerFruitSimpleActionPerformed(evt);
            }
        });
        panelBoutonsValiderAnnuler.add(jButtonAnnulerFruitSimple);

        getContentPane().add(panelBoutonsValiderAnnuler, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderFruitSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderFruitSimpleActionPerformed
        // TODO add your handling code here:
        if(this.jTextFieldPrixValide()){
            try{
                
                double prixJus = Double.parseDouble(this.jTextFieldPrixSalade.getText());
                OrigineProduit origineJus = (OrigineProduit) this.jComboBoxOrigineSalade.getSelectedItem();
                SaladeFruits salade = new SaladeFruits(prixJus,origineJus);
                
                for(FruitSimple fruit : fruits){
                    salade.ajoutFruit(fruit);
                }
                
                ControleurFruit cf = (ControleurFruit)this.mVP.getControleur();
                try{
                    cf.ajoutProduit(salade);
                }catch (Exception e){
                    System.err.println(e);
                }
                
            }catch(Exception e){
                System.err.println(e);
            }
            this.dispose();
            this.pack();
        }else{
            System.err.println("Vous devez renseigner le prix du fruit correctement !\nOu alors le fruit est boycotté !");
        }
    }//GEN-LAST:event_jButtonValiderFruitSimpleActionPerformed

    private void jButtonAnnulerFruitSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerFruitSimpleActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.pack();
    }//GEN-LAST:event_jButtonAnnulerFruitSimpleActionPerformed

    private void jButtonAjoutFruitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjoutFruitActionPerformed
        JTextField prixFruitTextField = new JTextField();
        JComboBox<String> origineFruitComboBox = new JComboBox<String>();
        JComboBox<String> typeFruitSimpleComboBox = new JComboBox<String>();
        
        DefaultComboBoxModel<OrigineProduit> modelOrigine = new DefaultComboBoxModel<>(OrigineProduit.values());
        origineFruitComboBox.setModel((ComboBoxModel) modelOrigine);
        
        DefaultComboBoxModel<TypeFruitSimple> modelType = new DefaultComboBoxModel<>(TypeFruitSimple.values());
        typeFruitSimpleComboBox.setModel((ComboBoxModel) modelType);
        
        Object[] message = {
            "Prix du fruit : ", prixFruitTextField,
            "Origine du fruit : ", origineFruitComboBox,
            "Type du fruit : ", typeFruitSimpleComboBox
        };

        int option = JOptionPane.showConfirmDialog(null, message, "Ajout fruit", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION) {
            TypeFruitSimple typeFruit = (TypeFruitSimple) typeFruitSimpleComboBox.getSelectedItem();
            OrigineProduit origineProduit = (OrigineProduit) origineFruitComboBox.getSelectedItem();
            double prix = Double.parseDouble(prixFruitTextField.getText());
            
            FruitFactory fruitFactory = new FruitFactory();
            FruitSimple fruitSimple = fruitFactory.creerFruitSimple(prix,origineProduit, typeFruit);
            
            fruits.add(fruitSimple);
            
            String chaineFruit = "";
            for(FruitSimple fruit : fruits){
                chaineFruit+=fruit.toString()+"\n";
            }
            this.jTextArea1.setText(chaineFruit);
        } 
    }//GEN-LAST:event_jButtonAjoutFruitActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjoutFruit;
    private javax.swing.JButton jButtonAnnulerFruitSimple;
    private javax.swing.JButton jButtonValiderFruitSimple;
    private javax.swing.JComboBox<String> jComboBoxOrigineSalade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldPrixSalade;
    private javax.swing.JLabel labelOrigineSalade;
    private javax.swing.JLabel labelPrixSalade;
    private javax.swing.JPanel panelBoutonsValiderAnnuler;
    private javax.swing.JPanel panelPrixQteFruitSimple;
    private javax.swing.JPanel panelTypeOrigineFruitSimple;
    // End of variables declaration//GEN-END:variables
    
    public VuePanier getVuePanier(){
        return this.mVP;
    }
    
    public void setVuePanier(VuePanier vuePanier){
        this.mVP = vuePanier;
    }
    
    public Controleur getControleur(){
        return this.mControleur;
    }
    
    @Override
    public void addControleur(Controleur c){
        this.mControleur=c;
    }
    
    @Override
    public void update(Observable m, Object o){
        //this.mVP.remplirListe();
    }
}
