/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package fr.ufrsciencestech.panier.view;

import fr.ufrsciencestech.panier.controler.Controleur;
import java.util.Observable;

/**
 *
 * @author nb654417
 */
public class VueGAWT extends java.awt.Frame implements VueG  {

    /**
     * Creates new form VueGAWT
     */
    public VueGAWT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new java.awt.Panel();
        plusButton = new java.awt.Button();
        nbFruits = new java.awt.Label();
        minusButton = new java.awt.Button();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(new java.awt.GridLayout());

        mainPanel.setName("Panier"); // NOI18N
        mainPanel.setLayout(new java.awt.GridLayout(0, 1));

        plusButton.setLabel("+");
        mainPanel.add(plusButton);

        nbFruits.setAlignment(java.awt.Label.CENTER);
        nbFruits.setText("0");
        mainPanel.add(nbFruits);

        minusButton.setLabel("-");
        mainPanel.add(minusButton);

        add(mainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel mainPanel;
    private java.awt.Button minusButton;
    private java.awt.Label nbFruits;
    private java.awt.Button plusButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addControleur(Controleur c){
        this.plusButton.addActionListener(c);
        this.minusButton.addActionListener(c);
    }
    
    @Override
    public void update(Observable m, Object o){     //This method is called whenever the observed object is changed
        this.nbFruits.setText(((Integer) o).toString());
    }
}
