/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fr.ufrsciencestech.panier.view;

import fr.ufrsciencestech.panier.controler.Controleur;
import fr.ufrsciencestech.panier.model.FruitFactory;
import fr.ufrsciencestech.panier.model.Produit;
import fr.ufrsciencestech.panier.model.FruitSimple;
import fr.ufrsciencestech.panier.model.JusBanane;
import fr.ufrsciencestech.panier.model.JusCerise;
import fr.ufrsciencestech.panier.model.OrigineProduit;
import fr.ufrsciencestech.panier.model.SaladeFruits;
import static fr.ufrsciencestech.panier.model.TypeProduit.JusBanane;
import static fr.ufrsciencestech.panier.model.TypeProduit.JusCerise;
import static fr.ufrsciencestech.panier.model.TypeProduit.SaladeFruits;
import javax.swing.*;

/**
 * Vue pour modifier un produit
 * @author pt454976
 */
public class VueModifProduit extends javax.swing.JFrame{
    /**
     * Le produit a modifier
     */
    private Produit mProduit;
    /**
     * Le controleur
     */
    private Controleur mControleur;
    /**
     * Vue parente
     */
    private VuePanier mVP;
    /**
     * Quantite de produit a modifier
     */
    private int mQuantite;

    /**
     * Constructeur
     * @param produit le produit a modifier
     * @param quantite la quantite de produit a modifier
     * @param vp le parent
     * @param controleur le controleur
     */
    public VueModifProduit(Produit produit, int quantite, VuePanier vp, Controleur controleur) {
        initComponents();
        this.mProduit = produit;
        this.mQuantite = quantite;
        this.mControleur = controleur;
        this.mVP = vp;
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        initDatas();
    }
    
    /**
     * Initialise les models des comboboxs et spinners
     */
    void initDatas(){
                
        DefaultComboBoxModel<OrigineProduit> modelOrigineProduit = new DefaultComboBoxModel<>(OrigineProduit.values());
        this.jComboBoxOrigineProduits.setModel((ComboBoxModel)modelOrigineProduit);
        this.jComboBoxOrigineProduits.setSelectedItem(this.mProduit.getOrigine());
        
        this.jTextFieldPrixProduits.setText(Double.toString(this.mProduit.getPrix()));
        
        this.jSpinnerQuantite.setModel(new SpinnerNumberModel(1, 0, this.mQuantite, 1));
    }
    
    /**
     * Verifie le prix
     * @return 
     */
    boolean jTextFieldPrixValide(){
        try{
            String text = this.jTextFieldPrixProduits.getText();
            double prix = Double.parseDouble(text);
            return true;
        }catch(Exception e){
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTop = new javax.swing.JPanel();
        jPanelInfosProduits = new javax.swing.JPanel();
        jLabelPrixProduits = new javax.swing.JLabel();
        jTextFieldPrixProduits = new javax.swing.JTextField();
        jLabelOrigineProduits = new javax.swing.JLabel();
        jComboBoxOrigineProduits = new javax.swing.JComboBox<>();
        jPanelQuantite = new javax.swing.JPanel();
        jLabelQuantite = new javax.swing.JLabel();
        jSpinnerQuantite = new javax.swing.JSpinner();
        jPanelBottom = new javax.swing.JPanel();
        jButtonValider = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modification");
        setPreferredSize(new java.awt.Dimension(400, 150));
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jPanelTop.setLayout(new java.awt.GridLayout(2, 1));

        jLabelPrixProduits.setText("Prix des produits : ");
        jPanelInfosProduits.add(jLabelPrixProduits);
        jPanelInfosProduits.add(jTextFieldPrixProduits);

        jLabelOrigineProduits.setText("Origine des produits : ");
        jPanelInfosProduits.add(jLabelOrigineProduits);

        jPanelInfosProduits.add(jComboBoxOrigineProduits);

        jPanelTop.add(jPanelInfosProduits);

        jLabelQuantite.setText("Quantité de produits à modifier : ");
        jPanelQuantite.add(jLabelQuantite);
        jPanelQuantite.add(jSpinnerQuantite);

        jPanelTop.add(jPanelQuantite);

        getContentPane().add(jPanelTop);

        jButtonValider.setText("Valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });
        jPanelBottom.add(jButtonValider);

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });
        jPanelBottom.add(jButtonAnnuler);

        getContentPane().add(jPanelBottom);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Bouton de validation,
     * recupere les donnees de la vue et modifie le produit dans le panier
     * @param evt 
     */
    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
        if(this.jTextFieldPrixValide()){
            int quantiteAModif = (int)this.jSpinnerQuantite.getValue();
            double prixModif = Double.parseDouble(this.jTextFieldPrixProduits.getText());
            OrigineProduit origineModif = (OrigineProduit)this.jComboBoxOrigineProduits.getSelectedItem();
            
            Produit prodInit;
            Produit prodModif;
            switch(this.mProduit.getTypeProduit()){
                case FruitSimple:
                    FruitSimple fruit = (FruitSimple) this.mProduit;
                    prodInit = FruitFactory.creerFruitSimple(fruit.getPrix(), fruit.getOrigine(), fruit.getTypeFruitSimple());
                    prodModif = FruitFactory.creerFruitSimple(prixModif,origineModif,fruit.getTypeFruitSimple());
                    break;
                case SaladeFruits:
                    SaladeFruits salade = (SaladeFruits) this.mProduit;
                    prodInit = FruitFactory.creerSaladeFruits(salade.getPrix(), salade.getOrigine());
                    prodModif = FruitFactory.creerSaladeFruits(prixModif,origineModif);
                    break;
                case JusCerise:
                    JusCerise jusC = (JusCerise) this.mProduit;
                    prodInit = FruitFactory.creerJusCerise(jusC.getPrix(),jusC.getOrigine(),jusC.getFruit());
                    prodModif = FruitFactory.creerJusCerise(prixModif,origineModif,jusC.getFruit());
                    break;
                case JusBanane:
                    JusBanane jusB = (JusBanane) this.mProduit;
                    prodInit = FruitFactory.creerJusCerise(jusB.getPrix(),jusB.getOrigine(),jusB.getFruit());
                    prodModif = FruitFactory.creerJusBanane(prixModif,origineModif,jusB.getFruit());
                    break;
                default:
                    throw new AssertionError(this.mProduit.getTypeProduit().name());
                
            }            
            this.mControleur.produitModif(prodInit, prodModif, quantiteAModif);
            
            this.dispose();
            this.pack();
        }
        else{
            System.err.println("Prix non valide !");
        }
    }//GEN-LAST:event_jButtonValiderActionPerformed

    /**
     * Bouton d'annulation, ferme la vue
     * @param evt 
     */
    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        this.dispose();
        this.pack();
    }//GEN-LAST:event_jButtonAnnulerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JComboBox<String> jComboBoxOrigineProduits;
    private javax.swing.JLabel jLabelOrigineProduits;
    private javax.swing.JLabel jLabelPrixProduits;
    private javax.swing.JLabel jLabelQuantite;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JPanel jPanelInfosProduits;
    private javax.swing.JPanel jPanelQuantite;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JSpinner jSpinnerQuantite;
    private javax.swing.JTextField jTextFieldPrixProduits;
    // End of variables declaration//GEN-END:variables
    
    public Produit getProduit(){
        return this.mProduit;
    }
    
    public int getQuantite(){
        return this.mQuantite;
    }
    
    public void setProduit(Produit produit){
        this.mProduit = produit;
    }
    
    public void setQuantite(int quantite){
        this.mQuantite = quantite;
    }
}
