/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fr.ufrsciencestech.panier.view;

import fr.ufrsciencestech.panier.controler.Controleur;
import fr.ufrsciencestech.panier.model.Produit;
import fr.ufrsciencestech.panier.model.FruitSimple;
import fr.ufrsciencestech.panier.model.OrigineProduit;
import fr.ufrsciencestech.panier.model.Panier;
import fr.ufrsciencestech.panier.model.TypeFruitSimple;
import javax.swing.*;
import java.awt.*;
import java.util.Observable;

/**
 *
 * @author pt454976
 */
public class VueModifProduit extends javax.swing.JFrame implements VueG{
    private Produit mProduit;
    private Controleur mControleur;
    private VuePanier mVP;
    private int mQuantite;

    /**
     * Creates new form VueModifFruit
     */
    public VueModifProduit(Produit produit, int quantite, VuePanier vp, Controleur controleur) {
        initComponents();
        this.mProduit = produit;
        this.mQuantite = quantite;
        this.mControleur = controleur;
        this.mVP = vp;
        
        initDatas();
    }
    
    void initDatas(){
        
        this.mVP.getPanier().addObserver(this);
        
        DefaultComboBoxModel<OrigineProduit> modelOrigineProduit = new DefaultComboBoxModel<>(OrigineProduit.values());
        this.jComboBoxOrigineProduits.setModel((ComboBoxModel)modelOrigineProduit);
        this.jComboBoxOrigineProduits.setSelectedItem(this.mProduit.getOrigine());
        
        this.jTextFieldPrixProduits.setText(Double.toString(this.mProduit.getPrix()));
        
        this.jSpinnerQuantite.setModel(new SpinnerNumberModel(1, 0, this.mQuantite, 1));
    }
    
    boolean jTextFieldPrixValide(){
        try{
            String text = this.jTextFieldPrixProduits.getText();
            double prix = Double.parseDouble(text);
            return true;
        }catch(Exception e){
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTop = new javax.swing.JPanel();
        jPanelInfosProduits = new javax.swing.JPanel();
        jLabelPrixProduits = new javax.swing.JLabel();
        jTextFieldPrixProduits = new javax.swing.JTextField();
        jLabelOrigineProduits = new javax.swing.JLabel();
        jComboBoxOrigineProduits = new javax.swing.JComboBox<>();
        jPanelQuantite = new javax.swing.JPanel();
        jLabelQuantite = new javax.swing.JLabel();
        jSpinnerQuantite = new javax.swing.JSpinner();
        jPanelBottom = new javax.swing.JPanel();
        jButtonValider = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jPanelTop.setLayout(new java.awt.GridLayout(2, 1));

        jLabelPrixProduits.setText("Prix des produits : ");
        jPanelInfosProduits.add(jLabelPrixProduits);
        jPanelInfosProduits.add(jTextFieldPrixProduits);

        jLabelOrigineProduits.setText("Origine des produits : ");
        jPanelInfosProduits.add(jLabelOrigineProduits);

        jPanelInfosProduits.add(jComboBoxOrigineProduits);

        jPanelTop.add(jPanelInfosProduits);

        jLabelQuantite.setText("Quantité de produits à modifier : ");
        jPanelQuantite.add(jLabelQuantite);
        jPanelQuantite.add(jSpinnerQuantite);

        jPanelTop.add(jPanelQuantite);

        getContentPane().add(jPanelTop);

        jButtonValider.setText("Valider");
        jButtonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValiderActionPerformed(evt);
            }
        });
        jPanelBottom.add(jButtonValider);

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });
        jPanelBottom.add(jButtonAnnuler);

        getContentPane().add(jPanelBottom);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValiderActionPerformed
        // TODO add your handling code here:
        if(this.jTextFieldPrixValide()){
            int quantiteAModif = (int)this.jSpinnerQuantite.getValue();
            double prixModif = Double.parseDouble(this.jTextFieldPrixProduits.getText());
            OrigineProduit origineModif = (OrigineProduit)this.jComboBoxOrigineProduits.getSelectedItem();
            
            Produit prodInit = this.mProduit;
            Produit prodModif = this.mProduit;
            prodModif.setPrix(prixModif);
            prodModif.setOrigine(origineModif);
            
            this.mControleur.produitModif(prodInit, prodModif, quantiteAModif);
            
            this.dispose();
            this.pack();
        }
        else{
            System.err.println("Prix non valide !");
        }
    }//GEN-LAST:event_jButtonValiderActionPerformed

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.pack();
    }//GEN-LAST:event_jButtonAnnulerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonValider;
    private javax.swing.JComboBox<String> jComboBoxOrigineProduits;
    private javax.swing.JLabel jLabelOrigineProduits;
    private javax.swing.JLabel jLabelPrixProduits;
    private javax.swing.JLabel jLabelQuantite;
    private javax.swing.JPanel jPanelBottom;
    private javax.swing.JPanel jPanelInfosProduits;
    private javax.swing.JPanel jPanelQuantite;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JSpinner jSpinnerQuantite;
    private javax.swing.JTextField jTextFieldPrixProduits;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable m, Object o){
        //this.mPanier= (Panier)o;
        this.mVP.remplirListe();
    }

    @Override
    public void addControleur(Controleur c) {
        this.mControleur=c;
    }
    
    public Produit getProduit(){
        return this.mProduit;
    }
    
    public int getQuantite(){
        return this.mQuantite;
    }
    
    public void setProduit(Produit produit){
        this.mProduit = produit;
    }
    
    public void setQuantite(int quantite){
        this.mQuantite = quantite;
    }
}
