/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fr.ufrsciencestech.panier.view;

import javax.swing.*;
import java.awt.*;
import java.util.Observable;

import fr.ufrsciencestech.panier.controler.*;
import fr.ufrsciencestech.panier.model.*;
import static fr.ufrsciencestech.panier.model.TypeProduit.JusBanane;
import static fr.ufrsciencestech.panier.model.TypeProduit.JusCerise;

/**
 *
 * @author pt454976
 */
public class VuePanelFruit extends javax.swing.JPanel {
    private Produit mProduit;
    private VuePanier mVP;
    private Controleur mControleur;
    private int mQuantite;
    
    /**
     * Creates new form VuePanelFruit
     */
    public VuePanelFruit(Produit p, VuePanier vp, int qte, Controleur controleur) {
        initComponents();
        this.mProduit = p;
        this.mVP = vp;
        this.mQuantite = qte;
        this.mControleur = controleur;
       
        initDatas(this.mProduit);
    }
    
    void initDatas(Produit p){
        if(p.getTypeProduit().equals(TypeProduit.FruitSimple)){
            FruitSimple fruit = (FruitSimple)this.mProduit;
            this.contFruit.setText(fruit.getTypeFruitSimple().toString());
        }
        if(p.getTypeProduit().equals(TypeProduit.JusCerise)){
            JusCerise fruit = (JusCerise)this.mProduit;
            this.contFruit.setText(fruit.getTypeProduit().toString());
        }
        if(p.getTypeProduit().equals(TypeProduit.JusBanane)){
            JusBanane fruit = (JusBanane)this.mProduit;
            this.contFruit.setText(fruit.getTypeProduit().toString());
        }
        this.contOrigine.setText(this.mProduit.getOrigine() + " ");
        this.contQuantite.setText(Integer.toString(this.mQuantite) + " ");
        this.contPrixUnit.setText(this.mProduit.getPrix() + "€ ");
        this.contPrixTotal.setText(Double.toString(this.mProduit.getPrix() * this.mQuantite) + "€ ");   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelFruit = new javax.swing.JLabel();
        contFruit = new javax.swing.JLabel();
        labelOrigine = new javax.swing.JLabel();
        contOrigine = new javax.swing.JLabel();
        labelQuantite = new javax.swing.JLabel();
        contQuantite = new javax.swing.JLabel();
        ajoutQteFruit = new javax.swing.JButton();
        retireQteFruit = new javax.swing.JButton();
        modifQteFruit = new javax.swing.JButton();
        labelPrixUnit = new javax.swing.JLabel();
        contPrixUnit = new javax.swing.JLabel();
        labelPrixTotal = new javax.swing.JLabel();
        contPrixTotal = new javax.swing.JLabel();

        labelFruit.setText("Produit :");
        add(labelFruit);
        add(contFruit);

        labelOrigine.setText("| Origine : ");
        add(labelOrigine);
        add(contOrigine);

        labelQuantite.setText("| Qte : ");
        add(labelQuantite);
        add(contQuantite);

        ajoutQteFruit.setText("+");
        ajoutQteFruit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutQteFruitActionPerformed(evt);
            }
        });
        add(ajoutQteFruit);

        retireQteFruit.setText("-");
        retireQteFruit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retireQteFruitActionPerformed(evt);
            }
        });
        add(retireQteFruit);

        modifQteFruit.setText("Edit");
        modifQteFruit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifQteFruitActionPerformed(evt);
            }
        });
        add(modifQteFruit);

        labelPrixUnit.setText("Prix unitaire : ");
        add(labelPrixUnit);
        add(contPrixUnit);

        labelPrixTotal.setText("| Prix total : ");
        add(labelPrixTotal);
        add(contPrixTotal);
    }// </editor-fold>//GEN-END:initComponents

    private void ajoutQteFruitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutQteFruitActionPerformed
        // TODO add your handling code here:
        ControleurFruit cf = (ControleurFruit)this.mVP.getControleur();
        Produit produitAjout;
        switch(mProduit.getTypeProduit()){
            case FruitSimple:
                produitAjout = (FruitSimple) this.mProduit;
                break;
            case SaladeFruits:
                produitAjout = (SaladeFruits) this.mProduit;
                break;
            case JusCerise:
                produitAjout = (JusCerise) this.mProduit;
                break;
            case JusBanane:
                produitAjout = (JusBanane) this.mProduit;
                break;
            default:
                throw new AssertionError(mProduit.getTypeProduit().name());      
        }
        
        
        try{
            this.mVP.getControleur().ajoutProduit(produitAjout);
        }catch (Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_ajoutQteFruitActionPerformed

    private void retireQteFruitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retireQteFruitActionPerformed
        // TODO add your handling code here:
        try{
            this.mVP.getControleur().retraitProduit(this.mProduit);
        }catch (Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_retireQteFruitActionPerformed

    private void modifQteFruitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifQteFruitActionPerformed
        // TODO add your handling code here:
        VueModifProduit vmf = new VueModifProduit(this.mProduit, this.mQuantite, this.mVP, this.mControleur);
        vmf.setVisible(true);
    }//GEN-LAST:event_modifQteFruitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutQteFruit;
    private javax.swing.JLabel contFruit;
    private javax.swing.JLabel contOrigine;
    private javax.swing.JLabel contPrixTotal;
    private javax.swing.JLabel contPrixUnit;
    private javax.swing.JLabel contQuantite;
    private javax.swing.JLabel labelFruit;
    private javax.swing.JLabel labelOrigine;
    private javax.swing.JLabel labelPrixTotal;
    private javax.swing.JLabel labelPrixUnit;
    private javax.swing.JLabel labelQuantite;
    private javax.swing.JButton modifQteFruit;
    private javax.swing.JButton retireQteFruit;
    // End of variables declaration//GEN-END:variables


    public Produit getProduit() {
        return this.mProduit;    
    }
    
    public VuePanier getVuePanier() {
        return this.mVP;
    }
    
    public int getQuantite(){
        return this.mQuantite;
    }
    
    public void setProduit(Produit mProduit) {
        this.mProduit = mProduit;
    }

    public void setVP(VuePanier mVP) {
        this.mVP = mVP;
    }
    
    public void setQuantite(int qte){
        this.mQuantite = qte;
    }
}