/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fr.ufrsciencestech.panier.view;

import fr.ufrsciencestech.panier.controler.*;
import fr.ufrsciencestech.panier.model.*;
import static fr.ufrsciencestech.panier.model.TypeProduit.JusBanane;
import static fr.ufrsciencestech.panier.model.TypeProduit.JusCerise;

/**
 * Vue pour afficher un produit
 * @author pt454976
 */
public class VuePanelProduit extends javax.swing.JPanel {
    /**
     * Le produit affiche
     */
    private Produit mProduit;
    /**
     * Vue parente
     */
    private VuePanier mVP;
    /**
     * Le controleur
     */
    private Controleur mControleur;
    /**
     * Quantite de produit dans le panier
     */
    private int mQuantite;
    
    /**
     * Constructeur de la vue
     * @param p le produit a afficher
     * @param vp le parent
     * @param qte la quantite de produit
     * @param controleur le controleur
     */
    public VuePanelProduit(Produit p, VuePanier vp, int qte, Controleur controleur) {
        initComponents();
        this.mProduit = p;
        this.mVP = vp;
        this.mQuantite = qte;
        this.mControleur = controleur;
       
        initDatas();
    }
    
    /**
     * Initialise les labels de la vue avec les donnes du produit
     */
    void initDatas(){
        if(this.mProduit.getTypeProduit().equals(TypeProduit.FruitSimple)){
            FruitSimple fruit = (FruitSimple)this.mProduit;
            this.contFruit.setText(fruit.getTypeFruitSimple().toString());
        }
        else{
            this.contFruit.setText(this.mProduit.getTypeProduit().toString());
        }
        this.contOrigine.setText(this.mProduit.getOrigine() + " ");
        this.contQuantite.setText(Integer.toString(this.mQuantite) + " ");
        this.contPrixUnit.setText(this.mProduit.getPrix() + "€ ");
        this.contPrixTotal.setText(Double.toString(this.mProduit.getPrix() * this.mQuantite) + "€ ");   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelFruit = new javax.swing.JLabel();
        contFruit = new javax.swing.JLabel();
        labelOrigine = new javax.swing.JLabel();
        contOrigine = new javax.swing.JLabel();
        labelQuantite = new javax.swing.JLabel();
        contQuantite = new javax.swing.JLabel();
        ajoutQteFruit = new javax.swing.JButton();
        retireQteFruit = new javax.swing.JButton();
        modifQteFruit = new javax.swing.JButton();
        labelPrixUnit = new javax.swing.JLabel();
        contPrixUnit = new javax.swing.JLabel();
        labelPrixTotal = new javax.swing.JLabel();
        contPrixTotal = new javax.swing.JLabel();

        labelFruit.setText("Produit :");
        add(labelFruit);
        add(contFruit);

        labelOrigine.setText("| Origine : ");
        add(labelOrigine);
        add(contOrigine);

        labelQuantite.setText("| Qte : ");
        add(labelQuantite);
        add(contQuantite);

        ajoutQteFruit.setText("+");
        ajoutQteFruit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutQteFruitActionPerformed(evt);
            }
        });
        add(ajoutQteFruit);

        retireQteFruit.setText("-");
        retireQteFruit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retireQteFruitActionPerformed(evt);
            }
        });
        add(retireQteFruit);

        modifQteFruit.setText("Edit");
        modifQteFruit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifQteFruitActionPerformed(evt);
            }
        });
        add(modifQteFruit);

        labelPrixUnit.setText("Prix unitaire : ");
        add(labelPrixUnit);
        add(contPrixUnit);

        labelPrixTotal.setText("| Prix total : ");
        add(labelPrixTotal);
        add(contPrixTotal);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Bouton d'ajout de produit
     * @param evt 
     */
    private void ajoutQteFruitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutQteFruitActionPerformed
        Produit produitAjout;
        switch(mProduit.getTypeProduit()){
            case FruitSimple:
                produitAjout = (FruitSimple) this.mProduit;
                break;
            case SaladeFruits:
                produitAjout = (SaladeFruits) this.mProduit;
                break;
            case JusCerise:
                produitAjout = (JusCerise) this.mProduit;
                break;
            case JusBanane:
                produitAjout = (JusBanane) this.mProduit;
                break;
            default:
                throw new AssertionError(mProduit.getTypeProduit().name());      
        }
        
        
        try{
            this.mVP.getControleur().ajoutProduit(produitAjout);
        }catch (Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_ajoutQteFruitActionPerformed

    /**
     * Bouton de suppression d'un produit
     * @param evt 
     */
    private void retireQteFruitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retireQteFruitActionPerformed
        try{
            this.mVP.getControleur().retraitProduit(this.mProduit);
        }catch (Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_retireQteFruitActionPerformed

    /**
     * Bouton de modification d'un produit
     * @param evt 
     */
    private void modifQteFruitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifQteFruitActionPerformed
        VueModifProduit vmf = new VueModifProduit(this.mProduit, this.mQuantite, this.mVP, this.mControleur);
        vmf.setVisible(true);
    }//GEN-LAST:event_modifQteFruitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutQteFruit;
    private javax.swing.JLabel contFruit;
    private javax.swing.JLabel contOrigine;
    private javax.swing.JLabel contPrixTotal;
    private javax.swing.JLabel contPrixUnit;
    private javax.swing.JLabel contQuantite;
    private javax.swing.JLabel labelFruit;
    private javax.swing.JLabel labelOrigine;
    private javax.swing.JLabel labelPrixTotal;
    private javax.swing.JLabel labelPrixUnit;
    private javax.swing.JLabel labelQuantite;
    private javax.swing.JButton modifQteFruit;
    private javax.swing.JButton retireQteFruit;
    // End of variables declaration//GEN-END:variables

}