/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package fr.ufrsciencestech.panier.view;

import javax.swing.*;
import java.awt.*;

import fr.ufrsciencestech.panier.model.Fruit;

/**
 *
 * @author pt454976
 */
public class VuePanelFruit extends javax.swing.JPanel{
    Fruit f;
    /**
     * Creates new form VuePanelFruit
     */
    public VuePanelFruit(Fruit f, int qte) {
        initComponents();
        this.f = f;
        
        initPanel(f, qte);
    }
    
    void initPanel(Fruit f, int quantite){
        //this.contFruit.setText();
        this.contOrigine.setText(this.f.getOrigine());
        this.contQuantite.setText(Integer.toString(quantite));
        this.contPrixUnit.setText(this.f.getPrix() + "€");
        this.contPrixTotal.setText(Double.toString(this.f.getPrix() * quantite));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelFruit = new javax.swing.JLabel();
        contFruit = new javax.swing.JLabel();
        labelOrigine = new javax.swing.JLabel();
        contOrigine = new javax.swing.JLabel();
        labelQuantite = new javax.swing.JLabel();
        contQuantite = new javax.swing.JLabel();
        ajoutQteFruit = new javax.swing.JButton();
        retireQteFruit = new javax.swing.JButton();
        modifQteFruit = new javax.swing.JButton();
        labelPrixUnit = new javax.swing.JLabel();
        contPrixUnit = new javax.swing.JLabel();
        labelPrixTotal = new javax.swing.JLabel();
        contPrixTotal = new javax.swing.JLabel();

        labelFruit.setText("Fruit : ");
        add(labelFruit);
        add(contFruit);

        labelOrigine.setText("Origine : ");
        add(labelOrigine);
        add(contOrigine);

        labelQuantite.setText("Qte : ");
        add(labelQuantite);
        add(contQuantite);

        ajoutQteFruit.setText("+");
        add(ajoutQteFruit);

        retireQteFruit.setText("-");
        add(retireQteFruit);

        modifQteFruit.setText("Edit");
        add(modifQteFruit);

        labelPrixUnit.setText("Prix unitaire : ");
        add(labelPrixUnit);
        add(contPrixUnit);

        labelPrixTotal.setText("Prix total : ");
        add(labelPrixTotal);
        add(contPrixTotal);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutQteFruit;
    private javax.swing.JLabel contFruit;
    private javax.swing.JLabel contOrigine;
    private javax.swing.JLabel contPrixTotal;
    private javax.swing.JLabel contPrixUnit;
    private javax.swing.JLabel contQuantite;
    private javax.swing.JLabel labelFruit;
    private javax.swing.JLabel labelOrigine;
    private javax.swing.JLabel labelPrixTotal;
    private javax.swing.JLabel labelPrixUnit;
    private javax.swing.JLabel labelQuantite;
    private javax.swing.JButton modifQteFruit;
    private javax.swing.JButton retireQteFruit;
    // End of variables declaration//GEN-END:variables
}
