/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fr.ufrsciencestech.panier.view;

import fr.ufrsciencestech.panier.controler.Controleur;
import fr.ufrsciencestech.panier.controler.ControleurFruit;
import fr.ufrsciencestech.panier.model.*;

import javax.swing.*;
import java.awt.*;
import java.util.*;

/**
 *
 * @author pt454976
 */
public class VuePanier extends javax.swing.JFrame implements VueG {
    private Panier mPanier;
    private Controleur mControleur;
    
    /*
    * une vue doit avoir un controlleur, on appellera ses méthodes pour modifier le model
    * le modèle (panier ou autre) doit être observé par une vue
    * les évènements des boutons sont gérés dans la vue elle-même
    *
        this.mVP.getPanier().addObserver(this);    
        ControleurFruit cf = new ControleurFruit();
        cf.setVue(this);
        cf.setModele(this.mVP.getPanier());
        this.addControleur(cf);
    */
    
    /**
     * Creates new form VuePanier
     */
    public VuePanier() {
        initComponents();
        this.setTitle("Panier");  
        this.setVisible(true);
    }
    
    public VuePanier(Controleur c, Panier p){
        initComponents();
        this.setTitle("Panier");
        this.setVisible(true);
        
        this.mControleur= c;
        this.mPanier= p;
    }
    
    void remplirListe(){
        double prixTotalPanier = 0;
        
        this.panelListeFruits.removeAll();
        this.panelListeFruits.revalidate();
        this.panelListeFruits.repaint();
        
        ArrayList<Produit> produitsAjoutes = new ArrayList<>();
        for(Produit produit : this.mPanier.getProduits()){
            if(!layoutContientProduit(produit, produitsAjoutes)){
                int quantite = compteQteFruits(produit, this.mPanier);
             
                VuePanelFruit vf = new VuePanelFruit(produit, this, quantite);
                
                this.panelListeFruits.add(vf);
                produitsAjoutes.add(produit);
                prixTotalPanier += quantite * produit.getPrix();
                
            }
        }
        
        this.contPrixTotalPanier.setText(Double.toString(prixTotalPanier) + "€ ");
    }
    
    boolean layoutContientProduit(Produit prodTest, ArrayList<Produit> produits){
        for(Produit produit : produits){
            if(prodTest.equals(produit)){
                return true;
            }
        }
        return false;
    }
    
    int compteQteFruits(Produit prodTest, Panier panier){
        int compteur = 0;
        for(Produit produit : panier.getProduits()){
            if(produit.equals(prodTest)) compteur++;
        }
        return compteur;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVuePanier = new javax.swing.JPanel();
        panelPanier = new javax.swing.JPanel();
        panelListeFruits = new javax.swing.JPanel();
        panelPrixTotalPanier = new javax.swing.JPanel();
        labelPrixTotalPanier = new javax.swing.JLabel();
        contPrixTotalPanier = new javax.swing.JLabel();
        panelBoutonsAjouts = new javax.swing.JPanel();
        jButtonAjouterFruit = new javax.swing.JButton();
        jButtonAjouterJus = new javax.swing.JButton();
        jButtonAjoutMacedoine = new javax.swing.JButton();
        jButtonAjoutSalade = new javax.swing.JButton();
        jButtonBoycotter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.GridLayout(1, 2));

        panelVuePanier.setLayout(new java.awt.GridLayout(1, 2));

        panelPanier.setLayout(new java.awt.BorderLayout());

        panelListeFruits.setLayout(new java.awt.GridLayout(0, 1));
        panelPanier.add(panelListeFruits, java.awt.BorderLayout.CENTER);

        labelPrixTotalPanier.setText("Prix total du panier : ");
        panelPrixTotalPanier.add(labelPrixTotalPanier);
        panelPrixTotalPanier.add(contPrixTotalPanier);

        panelPanier.add(panelPrixTotalPanier, java.awt.BorderLayout.SOUTH);

        panelVuePanier.add(panelPanier);

        panelBoutonsAjouts.setLayout(new java.awt.GridLayout(5, 1));

        jButtonAjouterFruit.setText("Ajouter fruit");
        jButtonAjouterFruit.setPreferredSize(new java.awt.Dimension(50, 23));
        panelBoutonsAjouts.add(jButtonAjouterFruit);

        jButtonAjouterJus.setText("Ajouter jus");
        jButtonAjouterJus.setPreferredSize(new java.awt.Dimension(50, 23));
        panelBoutonsAjouts.add(jButtonAjouterJus);

        jButtonAjoutMacedoine.setText("Ajouter macédoine");
        jButtonAjoutMacedoine.setPreferredSize(new java.awt.Dimension(50, 23));
        panelBoutonsAjouts.add(jButtonAjoutMacedoine);

        jButtonAjoutSalade.setText("Ajouter salade");
        jButtonAjoutSalade.setPreferredSize(new java.awt.Dimension(50, 23));
        panelBoutonsAjouts.add(jButtonAjoutSalade);

        jButtonBoycotter.setText("Boycotter");
        jButtonBoycotter.setPreferredSize(new java.awt.Dimension(50, 23));
        panelBoutonsAjouts.add(jButtonBoycotter);

        panelVuePanier.add(panelBoutonsAjouts);

        getContentPane().add(panelVuePanier);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contPrixTotalPanier;
    private javax.swing.JButton jButtonAjoutMacedoine;
    private javax.swing.JButton jButtonAjoutSalade;
    private javax.swing.JButton jButtonAjouterFruit;
    private javax.swing.JButton jButtonAjouterJus;
    private javax.swing.JButton jButtonBoycotter;
    private javax.swing.JLabel labelPrixTotalPanier;
    private javax.swing.JPanel panelBoutonsAjouts;
    private javax.swing.JPanel panelListeFruits;
    private javax.swing.JPanel panelPanier;
    private javax.swing.JPanel panelPrixTotalPanier;
    private javax.swing.JPanel panelVuePanier;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable m, Object o){
        this.mPanier= (Panier)o;
        this.remplirListe();
    }

    @Override
    public void addControleur(Controleur c) {
        this.mControleur=c;
    }
    
    public void setPanier(Panier p){
        this.mPanier = p;
    }
    
    public Panier getPanier() {
        return mPanier;
    }

    public Controleur getControleur() {
        return mControleur;
    }
}
